heartbeatsjp/happo-agent

model/monitor.go

If target node is in high load, command is also timeout.
So I change the status from `MONITOR_UNKNOWN` to `MONITOR_ERROR` when command timed out.
refs: https://github.com/heartbeatsjp/check_happo/issues/4

Avoid status flapping when command timed out

---

command/add.go

Add return error type value to `CmdAdd` for change to `cli.ActionFunc`, because `cli.App.Action` is deprecated.
https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

`CmdAdd` replace from `cli.App.Action` to `cli.ActionFunc`

---

README.md
collect/metrics.go
collect/metrics_test.go
command/daemon.go
command/metric.go
commands.go
glide.lock
glide.yaml
model/metric.go
util/util.go
util/util_test.go

Passive metrics collection feature.
- ex: `some_sensu_format_command | happo-agent append_metric --hostname $(uname -n) --endpoint <NEARBY_HAPPO_AGENT>`

new feature: passive metrics collection

---

README.md
command/daemon.go
commands.go
model/monitor.go
model/monitor_test.go
model/monitor_test_plugin
model/monitor_test_sleep
model/proxy.go
model/proxy_test.go
util/util.go
util/util_test.go
wercker.yml

When timeout occured, now return `400 Bad Request` .
I think this is not suitable.
- /monitor timeout (command timeout) should return `503 Service Unavailable`
- When command timeout occured, `504 Gateway Timeout` is not natural to me.
- /proxy timeout should return `504 Gateway Timeout` (now `502 Bad Gateway` )

change timeout status code

---

halib/tool.go
halib/tool_test.go

rename package lib to halib for dependency convenience.
`lib` tends to conflict to local package.

rename package lib to halib for dependency convenience

---

README.md
model/monitor.go
model/monitor_test.go
model/proxy.go

to be more intuitive.
- `/monitor`
- response 400 => 500 (Internal Server Error)
- if external command's stdout is empty, response message part is `stdout=, stderr={stderr}`
- if external command's stderr is **not** empty, response message part is `{stdout}, stderr={stderr}`
- `/proxy`
- response 400 => 500 (Internal Server Error)
- when origin returns 500, proxy returns 503

re-design response

---

README.md
autoscaling/autoscaling.go
autoscaling/autoscaling_test.go
command/daemon.go
halib/struct.go
model/autoscaling.go

`/autoscaling/instance/deregister` is new endpoint for deregister autoscaling instance.
an aim of this feature is not delete DB entry contain instance data, but deregister instance.
for that reason, deregister's implement is put empty value to `InstanceData.InstanceID` and `InstanceData.IP`.
Please review.

add feature autoscaling instance deregister

---

README.ja.md
README.md
autoscaling/autoscaling.go
autoscaling/autoscaling_test.go
command/daemon.go
halib/struct.go
model/autoscaling.go

`/autoscaling/delete` is new endpoint for delete autoscaling instances data.
It can be used when delete actual AutoScaling Group or reduce AutoScaling Group max size.
want to be delete one instance, in that case use `autoscaling/instances/deregister` API.
Please review.

add feature autoscaling delete

---

README.ja.md
README.md
autoscaling/autoscaling.go
autoscaling/autoscaling_test.go
command/daemon.go
halib/struct.go
model/autoscaling.go

Added new endpoint `/autoscale/instance/register`.
When do API request with parameter to this endpoint, happo-agent register instance data with dbms.
I thinking of using this endpoint when AutoScaling instance register self instance data after launch.

Autoscaling register instance

---

README.ja.md
README.md
contrib/development/README.md
contrib/development/docker_exec_test.sh
contrib/development/docker_run.sh

Add helper scripts for testing with docker on local.
These scripts are based on `wercker.yml` . we use these scripts while development happo-agent.

Add helper scripts for testing with docker on local

---

collect/metrics.go
collect/metrics_test.go

Fix #35 
- Plugin timeout is almost onetime, transient issue.
- One plugin blocks all metrics is not good behavior.
After merged, metrics collection continues from next plugin.

Fix #35 When timeout occured while collectiong metrics, does NOT abort collect metrics.

---

README.md
autoscaling/autoscaling.go
autoscaling/autoscaling_test.go
halib/constant.go
halib/struct.go
model/proxy.go
model/proxy_test.go

`/proxy` support AutoScaling. it behave when destination hostname prefix is match to `<AutoScaling Groupname>-<hostprefix>-`
- In case it can be resolved alias, proxy request to Auto Scaling instance.
- In case it can't be resolved alias, return dummy response from bastion.
- dummy response: `{"return_value":0,"message":"<alias> has not been assigned Instance\n"}`
- If failed monitor request to AutoScaling instance, execute refresh AutoScaling instances.
@netmarkjp  Please review.

Autoscaling proxy monitor

---

model/proxy.go
model/proxy_test.go

This patch implements proxy metric request to AutoScaling instance.
- In case it can be resolved alias, proxy request to Auto Scaling instance.
- In case it can't be resolved alias, return HTTP status 404 response from bastion.
@netmarkjp 
Please review.

Autoscaling proxy metric

---

autoscaling/autoscaling.go
model/proxy.go
model/proxy_test.go

This patch implements proxy `/metric/config/update` to AutoScaling instance.
- behave of proxy is same to other request type.
- proxy will update `MetricConfig` of instance data when request was successful.
@netmarkjp Please review.

Autoscaling proxy metric config update

---

autoscaling/autoscaling.go
model/proxy.go
model/proxy_test.go

This patch implements proxy inventory requests to AutoScaling instance.
Proxy will forward request to one instance. lowest numbered alias will be selected.
if can't find instances in specified Auto Scaling Group, return HTTP 503.
@netmarkjp Please review.

Autoscaling proxy inventory

---

command/daemon.go
commands.go
contrib/etc/default/happo-agent.env

In case happo-agent use as just only "Yet Another NRPE", collect metrics want to be disabled.
I think we should endpoint keep be enabled. To enable collect metrics in the future maybe.

add feature disable collect metrics

---

README.ja.md
README.md
command/daemon.go
command/resolve_alias.go
commands.go
halib/struct.go
model/autoscaling.go
util/util.go

I added `resolve_alias` subcommand in this PR.
This subcommand returns ip when alias specified in argument is already registered instance.
```
172.16.4.131
```
In case alias specified in argument is not registered instance or alias not found, returns blank.
```
```
@netmarkjp Please review.

subcommand resolve alias

---

command/daemon.go

On error while metrics collection, `log.Fatal` (exit) is too sensitive.
I think just logging is enough.

Change error handling behavior while metrics collection failed.

---

autoscaling/autoscaling.go
autoscaling/autoscaling_test.go

before:
- dummy-prod-ag-dummy-prod-app-1
- dummy-prod-ag-dummy-prod-app-2
- ...
after:
- dummy-prod-ag-dummy-prod-app-01
- dummy-prod-ag-dummy-prod-app-02
- ...
@netmarkjp 
Please review.

Alias of auto scaling instances are changed to suffix is zero padding

---

model/proxy.go

In proxy.go, `http.Client` and `http.Transport` are declared. However some parameters are not specified, allowing unexpected behave of http client.
ex) `IdleConnTimeout` is zero, it means HTTP Keep-Alive idle timeout is no limit
This PR fix it to use default settings and parameter override.

http.Client and http.Transport override default and use

---

model/proxy.go

In happo-agent 2.0.0, output error log when each requests to proxy when `autoscaing.yaml` not found.
```
2018-11-30 17:30:57 [error] failed to get autoscaling config: open /etc/happo-agent/autoscaling.yaml: no such file or directory
2018-11-30 17:30:59 [error] failed to get autoscaling config: open /etc/happo-agent/autoscaling.yaml: no such file or directory
2018-11-30 17:31:00 [error] failed to get autoscaling config: open /etc/happo-agent/autoscaling.yaml: no such file or directory
2018-11-30 17:31:00 [error] failed to get autoscaling config: open /etc/happo-agent/autoscaling.yaml: no such file or directory
```
I think it's unnecessary. Fixed it, if `autoscaling.yaml` is not exists, don't invoke `GetAutoScalingConfig()` but logging with INFO level.
@netmarkjp Please confirm.

Fix proxy logging

---

collect/metrics.go
collect/metrics_test.go
command/daemon.go
halib/struct.go
model/status.go

I fixed an issue that happo-agent saves an empty metric data when metric config not found.
@netmarkjp  
Please review.

Skip save metrics when metric config not found

---

README.md
autoscaling/autoscaling.go
command/daemon.go
halib/struct.go
model/autoscaling.go
model/autoscaling_test.go
util/util.go

I added `/autoscaling/health` API that can checks auto scaling node is available.
This API works on the bastion. A bastion's happo-agent receives a request in `/autoscaling/health/:alias`,  resolves the alias to IP address, after that send a request to `/` on that IP address.

Add /autoscaling/health API

---

wercker.yml

Maybe due to wercker's reason, daemontest always be over 4%...

Change daemontest CPU Usage threshold from 4% to 7%.

---

Gopkg.lock
Gopkg.toml

I fixed an issue that out of sync in this project.
```
$ dep status
Gopkg.lock is out of sync with imports and/or Gopkg.toml. Run `dep check` for details.
PROJECT                MISSING PACKAGES
github.com/pkg/errors  [github.com/pkg/errors]
input-digest mismatch
```
I run `dep ensure` to install above missing packages.
After that, I added new rules for "github.com/pkg/errors" in Gopkg.toml.
I run `dep ensure` again, and confirmed no change for Gopkg.lock.
NOTE:  My local environment dep version is v0.5.0.
```
$ dep version
dep:
version     : v0.5.0
build date  : 2018-07-26
git hash    : 224a564
go version  : go1.10.3
go compiler : gc
platform    : darwin/amd64
features    : ImportDuringSolve=false
```

Fix out of sync in this project

---

README.md
command/list_aliases.go
command/list_aliases_test.go
commands.go
util/util.go

I added subcommand named `list_aliases` that is a more human-readable interface compare with `/autoscaling` API.
```
$ happo-agent list_aliases
hb-autoscaling-web-01,192.0.2.1,i-0123456789abcdef0
hb-autoscaling-web-02,192.0.2.1,i-0123456789abcdef1
```
```
$ happo-agent list_aliases -all
hb-autoscaling-web-01,192.0.2.1,i-0123456789abcdef0
hb-autoscaling-web-02,192.0.2.1,i-0123456789abcdef1
hb-autoscaling-web-03,,
hb-autoscaling-web-04,,
```
This subcommand is useful when an operator logins server, in case an occurred incident affects the Auto Scaling Group.

`list_aliases` subcommand

---

command/remove.go
command/remove_test.go

This PR make the program output proper message when client management server returns `404 Not Found` as a response to `/manage/remove` .

Handle 404 in removing host

---

autoscaling/aws.go
command/daemon.go
model/autoscaling.go
model/proxy.go
model/proxy_test.go
model/status.go

Fix issue that region config for AWS client was hardcode to `ap-northeast-1`. And some refactor.
Fix
- Region config fetches by EC2 metadata and that set when creating AWS client.
Refactor
- Create AWS client at initializing daemon, and pass to the handler with [service injection](https://github.com/go-martini/martini/tree/v1.0#service-injection) (to avoid redundant code by error handling in each handle functions).

Fix AWS client

---

command/add.go
command/add_test.go
command/command_test.go
command/is_added.go
command/is_added_test.go
command/remove.go
command/remove_test.go

Current version of happo-agent prints only `Failed!` or `Unknown Status` when a client management server returns some error message. 
I think it would be helpful for the message to be displayed thus have implemented that.

Improve handling errors from client management server

---

command/is_added.go
command/is_added_test.go
command/remove.go
command/remove_test.go

Current version of happo-agent does client-side validation before request to management server but the result is not fully handled. This let happo-agent send empty request to the server.
This PR adds some handlers not to ignore those validation errors.

Fix client side validation

---

wercker.yml

In windows hosts, `zip` is better archive format than `tar.gz`.
I changed `wercker.yml` and tried running a build and deploy in the wercker that result is below.
Release page
- https://github.com/shiimaxx/happo-agent/releases/tag/pre-release

Change archive format for windows binary to zip

---

README.ja.md
README.md
model/proxy_test.go

I think following two parts of the README are incorrect.
- happo-agent does not actually support certificate using encrypted key.
- `request_json` parameter for `/proxy` request should not be a plaintext but base64 encoded JSON.
This PR fixes them.

Fix readme

---

autoscaling/autoscaling_test.go
collect/metrics.go
model/monitor.go
wercker.yml

Golang running on CI is old(golang:1.9.4).
Also, it is difficult to change the docker image being used. 
- Change the docker image used by wercker from netmarkjp/golang-build:1.9.4 to golang:1.13.3.
- Add new step in wercker.yml(go get module)
- Fix go vet warning.
- collect/metrics.go
- model/monitor.go 
Please review.

Update golang version(1.9.4 -> 1.13)
